const Db_personas = [
    {
      "_id": "650db68736c7df7830523129",
      "index": 0,
      "guid": "9a852733-ed76-48f7-a9f0-1dc8befc4e79",
      "balance": "$2,408.12",
      "picture": "http://placehold.it/32x32",
      "age": 30,
      "eyeColor": "brown",
      "name": "Claudio Monti",
      "email": "claudio@gmail.com",
      "role" : "admin",
      "password" : "1234text",
      "gender": "male",
      "company": "GORGANIC",  
      "phone": "+1 (931) 559-2595",
      "address": "815 Vanderveer Street, Sperryville, Hawaii, 3750",
      "about": "Sunt laboris deserunt duis aliqua veniam cillum anim laborum. Nisi amet nulla ea ex ex mollit officia sunt cillum. Nostrud in qui reprehenderit laboris culpa ullamco velit aute dolor culpa. Cillum aliquip proident ad excepteur fugiat est qui esse. Excepteur cupidatat ut sit ullamco sit adipisicing. Quis incididunt cupidatat aliquip commodo elit. Sunt eiusmod est pariatur et qui fugiat dolore commodo ipsum velit eu laboris mollit.\r\n",
      "registered": "2015-11-04T05:46:43 +03:00"
    },
    {
      "_id": "650db6870e3c1396e8b84021",
      "index": 1,
      "guid": "eebb4b3d-d0ea-4a83-8bd0-2461e40eab81",
      "balance": "$1,194.52",
      "picture": "http://placehold.it/32x32",
      "age": 26,
      "eyeColor": "brown",
      "name": "Yohana Ve",
      "email": "yoha@gmail.com",
      "password" : "1234",
       "role" : "user",
      "gender": "male",
      "company": "ISOPLEX",
      "phone": "+1 (955) 408-2503",
      "address": "107 Pine Street, Rehrersburg, Kansas, 8435",
      "about": "Eu esse Lorem consequat duis Lorem. Aliquip aute veniam voluptate pariatur proident ullamco in qui laborum. Eu consectetur laborum commodo labore mollit est nulla nisi consequat amet velit. Ut mollit ad minim excepteur dolore eu fugiat aliquip pariatur consectetur aliquip ad incididunt consequat. Ad aute dolor esse commodo ad ullamco non fugiat nisi duis.\r\n",
      "registered": "2020-08-10T02:49:44 +03:00"
    },
    {
      "_id": "650db687b64b805fea726b9a",
      "index": 2,
      "guid": "c10a7729-50a9-497c-853a-1d6381b3a704",
      "balance": "$2,796.06",
      "picture": "http://placehold.it/32x32",
      "age": 22,
      "eyeColor": "blue",
      "name": "Rodgers Stout",
      "gender": "male",
      "company": "FRENEX",
      "email": "rodgersstout@frenex.com",
      "phone": "+1 (986) 461-2307",
      "address": "212 Stillwell Avenue, Foscoe, South Dakota, 251",
      "about": "Fugiat quis ullamco ea exercitation excepteur sunt ut culpa quis aliquip ex. Non proident velit in do amet quis ad in sint quis ea elit mollit. Anim magna ipsum sunt nulla ex aliqua consectetur.\r\n",
      "registered": "2019-07-10T04:23:47 +03:00"
    },
    {
      "_id": "650db6878436f7fb5b51f5ef",
      "index": 3,
      "guid": "3b88b021-a90c-4743-9af2-0dbe1dceef13",
      "balance": "$3,575.97",
      "picture": "http://placehold.it/32x32",
      "age": 24,
      "eyeColor": "blue",
      "name": "Donaldson Gill",
      "gender": "male",
      "company": "GLASSTEP",
      "email": "donaldsongill@glasstep.com",
      "phone": "+1 (874) 465-3304",
      "address": "225 Wilson Street, Coinjock, Tennessee, 3430",
      "about": "Veniam et cillum id in proident elit ex est nisi excepteur culpa. Nulla Lorem enim occaecat laborum sunt officia eiusmod consectetur consectetur. Esse labore voluptate in duis reprehenderit do quis.\r\n",
      "registered": "2023-02-22T03:21:00 +03:00"
    },
    {
      "_id": "650db6873056dfd69559ee23",
      "index": 4,
      "guid": "7c0522ae-1b94-46af-a93f-feffdb2aa400",
      "balance": "$1,640.55",
      "picture": "http://placehold.it/32x32",
      "age": 35,
      "eyeColor": "brown",
      "name": "Hilda Cervantes",
      "gender": "female",
      "company": "ENDICIL",
      "email": "hildacervantes@endicil.com",
      "phone": "+1 (869) 564-3793",
      "address": "401 Sands Street, Wolcott, Missouri, 6274",
      "about": "Proident irure commodo irure ullamco eu pariatur anim ex veniam dolor sit. Voluptate est nisi quis laborum reprehenderit esse non. Quis Lorem id sint pariatur. Adipisicing sit ex reprehenderit non consectetur est est proident eu sit ad. Sunt nostrud anim est ipsum esse do officia adipisicing. Non amet mollit mollit ea velit. Adipisicing adipisicing anim aliquip cupidatat labore id proident esse sit qui enim eiusmod pariatur.\r\n",
      "registered": "2017-10-16T09:37:38 +03:00"
    }
  ]
  module.exports = Db_personas; 